### ISSUE TITLE
Just a fun addition

### ISSUE THREAD

**Issue by Aaidenplays** [learn-co-curriculum/phase-3-sequences#11]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195260?module_item_id=439018

### Concern

Its not a concern but another answer for the question `How would you retrieve the last two elements of a sequence if you don't know the length?` would be `s[-2:]`. seems like the shortest answer I could come up with. Might be nice to add it in if you so please. 

### Suggested Changes

add solution `s[-2:]` to the question How would you retrieve the last two elements of a sequence if you don't know the length?

**Comment by pgill97** [comment]
@professor-ben Added as a potential answer main and solution branch. [6c8c37c](https://github.com/learn-co-curriculum/phase-3-sequences/commit/6c8c37c245261ff65daf30f45efe99c698cb2ca4)
