### ISSUE TITLE
Further Discussion of .sort() and sorted()

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/phase-3-sequences#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195260?module_item_id=439018

### Concern

We really only scratch the surface of what you can use the .sort() and the sorted() methods can do. In cases where lists have more complex data structures inside of the - like dictionaries, lists, tuples, etc. (which we encounter in the Data Structures lab) - simply calling the .sort() and sorted() methods without any arguments won't be very useful. Students can certainly go read up Python docs to find out more for themselves about this method, and if that's our intention then I think this is fine. However, if our intention is to get students fully prepared to use .sort() and sorted(), then we'll want to discuss the use of functions to determine sorting criteria, etc.

**Comment by professor-ben** [comment]
I'm going to leave this open- we intend to expand on metaprogramming with `lambda` functions in the future. For now, this has to stay a bit more open for individual exploration. This is one of the first additions on the list after we QA the existing curriculum.

**Comment by professor-ben** [comment]
@Matt-Eva I've added a `lambda` mini-lesson in object inheritance. Please feel free to review if you have time- it's only about a page long.

**Comment by Matt-Eva** [comment]
I will, thanks Ben!
