### ISSUE TITLE
Print Empty Issue

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/phase-3-sequences#7]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195260?module_item_id=439018

### Concern

The first  assignment asks to print empty list ([]) but checks for printing nothing which I could only get to pass by skipping printing anything at all.

**Comment by jlboba** [comment]
Tested with the changes from commit https://github.com/learn-co-curriculum/phase-3-sequences/commit/dc052f25b46f7cd80131bdf6440a628600c6fb75 and it appears to work now. 

Please open a new issue if issue still persists!
